name: 🐛 Bug Report
description: Report a bug or unexpected behavior in AURA Protocol
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! This helps us improve AURA Protocol for everyone.
        
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: 🔍 Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: dropdown
    id: package
    attributes:
      label: 📦 Which package is affected?
      description: Select the package where you encountered the bug
      options:
        - "@aura/protocol (Core package)"
        - "reference-server (Next.js server)"
        - "reference-client (Example client)"
        - "CLI tools (aura-validate)"
        - "Documentation"
        - "Multiple packages"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 🐞 Current Behavior
      description: A clear and concise description of what the bug is
      placeholder: Describe what is happening...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: |
        Please provide information about your environment.
        Tip: You can run `node --version`, `npm --version`, and `pnpm --version` to get version info.
      value: |
        - OS: [e.g. macOS 13.0, Ubuntu 20.04, Windows 11]
        - Node.js version: [e.g. 18.17.0]
        - Package manager: [e.g. pnpm 8.6.0, npm 9.6.7]
        - Browser (if applicable): [e.g. Chrome 115, Firefox 116]
        - AURA Protocol version: [e.g. 1.0.0]
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: 📝 Code Sample
      description: |
        If applicable, provide a minimal code sample that reproduces the issue.
        This will help us understand and fix the bug more quickly.
      render: typescript
      placeholder: |
        // Your code here
        import { AuraManifest } from '@aura/protocol';
        
        const manifest: AuraManifest = {
          // ...
        };

  - type: textarea
    id: logs
    attributes:
      label: 📋 Relevant Logs
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📚 Additional Context
      description: |
        Add any other context about the problem here.
        Screenshots, network requests, or any other information that might be helpful.

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Would you be interested in contributing a fix for this issue?
      options:
        - label: I would be willing to submit a PR to fix this issue 